server:
  port: ${PORT:8080}

jasypt:
  encryptor:
    password: palamar

secret:
  key: ENC(3E7Jc0tOMwJADvlBOXsChnuRqmFNvOtWzqSRbM8zhZEYBi7S50VXtpv+FW8Wd/cO)

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:sa}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME:org.h2.Driver}
    type: ${SPRING_DATASOURCE_TYPE:org.apache.tomcat.jdbc.pool.DataSource}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${SPRING_JPA_DATABASE-PLATFORM:org.hibernate.dialect.H2Dialect}
        format_sql: true
    show-sql: true
