server:
  port: 8080

secret:
  key: test

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/refugees
    username: postgres
    password: QWE13579qwe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true