name: Test Git CD/CI Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-push:

    needs: test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean install -Djasypt.encryptor.password=palamar